import type { Metadata } from "next"
import './globals.css'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}
export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang = "en">
            <body className = "min-h-screen">
                {/* Layout UI */}
                {/* Place children where you want to render a page or nested layout*/}
                <main className = "min-h-screen">{children}</main>
            </body>
        </html>
    )
}